/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import controlador.Controlador_FRM_VentanaPrincipal;

/**
 *
 * @author RandyGUTI
 */
//clase que se muestra al inicio para seleccionar el tipo fuente de informacion a usar
public class FRM_SeleccionInicial extends javax.swing.JFrame {

    Controlador_FRM_VentanaPrincipal controlador;
    public FRM_SeleccionInicial(Controlador_FRM_VentanaPrincipal controlador) {
        initComponents();
        this.controlador=controlador;
        this.setLocation(500, 250);
    }
    //metodo que verifica si el radio button de Base de Datos esta seleccionado
    public boolean verificarBD()
    {
      return jrb_BaseDatos.isSelected();
    }
    //metodo que verifica si el radio button de Archivos Planos esta seleccionado
     public boolean verificarArchivosPlanos()
    {
      return jrb_Archivos.isSelected();
    }
     //metodo que verifica si el radio button de Archivos XML esta seleccionado
      public boolean verificarXML()
    {
      return jrb_XML.isSelected();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg_Tipo = new javax.swing.ButtonGroup();
        jrb_Archivos = new javax.swing.JRadioButton();
        jrb_BaseDatos = new javax.swing.JRadioButton();
        jrb_XML = new javax.swing.JRadioButton();
        jl_Titulo = new javax.swing.JLabel();

        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentHidden(java.awt.event.ComponentEvent evt) {
                formComponentHidden(evt);
            }
        });

        bg_Tipo.add(jrb_Archivos);
        jrb_Archivos.setText("Archivos Planos");

        bg_Tipo.add(jrb_BaseDatos);
        jrb_BaseDatos.setText("Base de Datos");

        bg_Tipo.add(jrb_XML);
        jrb_XML.setText("Archivos XML");

        jl_Titulo.setText("Seleccione la fuente que desea trabajar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(103, 103, 103)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jrb_XML)
                            .addComponent(jrb_BaseDatos)
                            .addComponent(jrb_Archivos)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addComponent(jl_Titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(62, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jl_Titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jrb_Archivos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jrb_BaseDatos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jrb_XML)
                .addContainerGap(61, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //metodo que al clickear x en la ventana carga los arraylist de las clases de metodos dependiendo el tipo 
    //de fuente de informacion seleccionada, y llama al metodo del controlador principal para levantar las ventanas de registro
    //, login o salir del programa
    private void formComponentHidden(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentHidden
        if(verificarBD())
        {
          controlador.conexion.realizarConexion();
          controlador.frm_MantenimientoCursos.controlador.metodosCursos.igualarArrayBD();
          controlador.frm_MantenimientoEstudiantes.controlador.metodosEstudiantes.igualarArrayBD();
          controlador.frm_Matricula.controlador.metodosMatricula.igualarArrayBD();
          controlador.metodos.igualarArrayBD();
        }
        if(verificarArchivosPlanos())
        {
          controlador.frm_MantenimientoCursos.controlador.metodosCursos.igualarArrayArchivos();
          controlador.frm_MantenimientoEstudiantes.controlador.metodosEstudiantes.igualarArrayArchivos();
          controlador.frm_Matricula.controlador.metodosMatricula.igualarArrayArchivos();
          controlador.metodos.igualarArrayArchivos();
        }
        if(verificarXML())
        {
          controlador.frm_MantenimientoEstudiantes.controlador.metodosEstudiantes.archivoXML.iniciarXML();
          controlador.frm_MantenimientoCursos.controlador.metodosCursos.archivoXML.iniciarXML();
          controlador.frm_Matricula.controlador.metodosMatricula.archivoXML.iniciarXML();
          controlador.metodos.archivoXML.iniciarXML();
          controlador.frm_MantenimientoEstudiantes.controlador.metodosEstudiantes.igualArrayXML();
          controlador.frm_MantenimientoCursos.controlador.metodosCursos.igualarArrayXML();
          controlador.frm_Matricula.controlador.metodosMatricula.igualArrayXML();
          controlador.metodos.igualArrayXML();
        }
        controlador.inicarPrograma();
    }//GEN-LAST:event_formComponentHidden

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bg_Tipo;
    private javax.swing.JLabel jl_Titulo;
    private javax.swing.JRadioButton jrb_Archivos;
    private javax.swing.JRadioButton jrb_BaseDatos;
    private javax.swing.JRadioButton jrb_XML;
    // End of variables declaration//GEN-END:variables
}
