/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import controlador.Controlador_FRM_VentanaLogin;
import javax.swing.JOptionPane;
import modelo.MetodosUsuario;

/**
 *
 * @author RandyGUTI
 */
public class FRM_VentanaLogin extends javax.swing.JFrame {

    /**
     * Creates new form FRM_VentanaLogin
     */
    
    Controlador_FRM_VentanaLogin controlador;
    public FRM_VentanaPrincipal frm_VentanaPrincipal;
    public MetodosUsuario metodos;
    
    public FRM_VentanaLogin(FRM_VentanaPrincipal frm_VentanaPrincipal,MetodosUsuario metodos) {
        initComponents();
        this.setLocation(500,200);
        this.setVisible(false);
        this.metodos=metodos;
        controlador=new Controlador_FRM_VentanaLogin(this);
        this.frm_VentanaPrincipal=frm_VentanaPrincipal;
        agregarEventos();
        
    }
    public void agregarEventos()
    {
      this.btn_Ingresar.addActionListener(controlador);
      this.btn_Salir.addActionListener(controlador);
    }
    public String devolverNombreUsuario()
    {
      return this.jt_Usuario.getText();
    }
    public boolean espaciosVacio()
    {
      if(jt_Usuario.getText().equals("") || jtp_Password.getText().equals(""))
          return true;
      else
          return false;
    }
    public String devolverPassword()
    {
      return this.jtp_Password.getText();
    }
    public void mostrarMensaje(String mensaje)
    {
        JOptionPane.showMessageDialog(null, mensaje);
    }
    public void resetearGUI()
    {
      this.jt_Usuario.setText("");
      this.jtp_Password.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jt_Usuario = new javax.swing.JTextField();
        jtp_Password = new javax.swing.JPasswordField();
        jl_Usuario = new javax.swing.JLabel();
        jl_Password = new javax.swing.JLabel();
        btn_Ingresar = new javax.swing.JButton();
        btn_Salir = new javax.swing.JButton();
        jl_TituloVentana = new javax.swing.JLabel();

        setBackground(new java.awt.Color(204, 204, 204));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentHidden(java.awt.event.ComponentEvent evt) {
                formComponentHidden(evt);
            }
        });

        jl_Usuario.setText("Usuario");

        jl_Password.setText("Contraseña");

        btn_Ingresar.setBackground(new java.awt.Color(51, 204, 0));
        btn_Ingresar.setText("Ingresar");

        btn_Salir.setBackground(new java.awt.Color(255, 0, 0));
        btn_Salir.setText("Salir");

        jl_TituloVentana.setFont(new java.awt.Font("Yu Gothic", 1, 24)); // NOI18N
        jl_TituloVentana.setText("Inicio de sesión");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jl_TituloVentana, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(btn_Ingresar)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btn_Salir))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jl_Password)
                                .addComponent(jl_Usuario))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jtp_Password, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jt_Usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(4, 4, 4))))
                .addContainerGap(72, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jl_TituloVentana, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jl_Usuario)
                    .addComponent(jt_Usuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jl_Password)
                    .addComponent(jtp_Password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_Ingresar)
                    .addComponent(btn_Salir))
                .addGap(48, 48, 48))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formComponentHidden(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentHidden
        resetearGUI();
        this.frm_VentanaPrincipal.setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_formComponentHidden

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Ingresar;
    private javax.swing.JButton btn_Salir;
    private javax.swing.JLabel jl_Password;
    private javax.swing.JLabel jl_TituloVentana;
    private javax.swing.JLabel jl_Usuario;
    private javax.swing.JTextField jt_Usuario;
    private javax.swing.JPasswordField jtp_Password;
    // End of variables declaration//GEN-END:variables
}
